apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arunvthangaraj/app-gitops.git
    targetRevision: main
    path: app-manifest
  destination:
    server: '{{.values.server}}'
    namespace: '{{.values.namespace}}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true